### ISSUE TITLE
使用React15+React Router4能兼容IE8吗?

### ISSUE THREAD

**Issue by blling** [jun0205/react-static-boilerplate#10]
看你中途有升级到React15 后面又退回来了，这是为啥呢?
使用React15+React Router4能做到兼容IE8吗?

**Comment by chats-is** [comment]
React 15 低版本是可以的，但是在 IE8 下面生成的 Label 包含一个 [Object object] ，因为无法确定这个会影响什么，就退回到 React 14 版本了，这个对 IE8 支持好点。
React Router4 我还没用过。是否兼容 IE8 需要你自己尝试了

**Comment by blling** [comment]
谢谢！ 现在你有在生产上使用`react-static-boilerplate`? :)
