### ISSUE TITLE
在IE8下无法运行

### ISSUE THREAD

**Issue by RationalPoet** [jun0205/react-static-boilerplate#13]
源码下到本地install、start之后在IE8浏览器下无法打开，一些打包后的代码报错。
例如：Symbol.for报错“缺少标识符”
在chrome下是能正常执行的。

**Comment by chats-is** [comment]
https://github.com/jun0205/react-static-boilerplate/issues/6

发布后的代码才可以在 IE8 下面运行，开发环境不可以。
