### ISSUE TITLE
IE8出错

### ISSUE THREAD

**Issue by ifooling** [jun0205/react-static-boilerplate#6]
SCRIPT1028: 缺少标识符、字符串或数字
browser-sync-client.js (1,22059)
SCRIPT1010: 缺少标识符
vendor.js (12729,11)
SCRIPT1028: 缺少标识符、字符串或数字
app.js (1312,81)

**Comment by chats-is** [comment]
发布后的代码才可以在 IE8 下面运行，请重新尝试。

**Comment by blling** [comment]
如果要发布后才能用IE8运行，那开发的时候怎么实时测试？
