### ISSUE TITLE
IE8中点击示例的直接跳转

### ISSUE THREAD

**Issue by kkkkkwong** [jun0205/react-static-boilerplate#7]
在 http://react-ie8.getfuli.com/  中，点击 Counter 页面跳转了
![image](https://user-images.githubusercontent.com/12517739/31371409-364e5a2a-ad56-11e7-93d2-e1cdf921d472.png)

**Comment by chats-is** [comment]
因为是放在 Github Pages 上面的，无法配置 URL 重写规则。

**Comment by kkkkkwong** [comment]
网站部署在本地mac OS
在虚拟机中测试，使用IE浏览器打开，选择IE8模式，报错
![image](https://user-images.githubusercontent.com/12517739/31372221-58caedda-ad5a-11e7-9c0f-d3a310481496.png)
是否需要修改其他东西才行？

**Comment by chats-is** [comment]
开发模式不能在 IE 8 下面运行， npm run build 一个出来，用 server 运行。

**Comment by kkkkkwong** [comment]
好的，了解，感谢解惑
