### ISSUE TITLE
路由不兼容ie8，火狐，谷歌等。。。

### ISSUE THREAD

**Issue by miaozilong** [jun0205/react-static-boilerplate#8]
火狐谷歌还好，在首页上点击的时候不会有问题
但是直接打开链接的时候就不行了   你看看你的链接  http://react-ie8.getfuli.com/counter

IE8是首页能打开，打开路由直接跳到404页面

**Comment by chats-is** [comment]
https://github.com/jun0205/react-static-boilerplate/issues/7
